FROM mcr.microsoft.com/vscode/devcontainers/python:3.9

# Install OpenCV dependencies
RUN apt-get update && apt-get install -y libgl1-mesa-glx libglib2.0-0

# Set the working directory
WORKDIR /workspace

# Copy requirements.txt if you have one
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt
